In [14]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt 
import seaborn as sns

In [15]:
df = pd.read_csv('train.txt',sep=';',header=None,names=['text','emotion'])
df.head()

                                                text  emotion
0                            i didnt feel humiliated  sadness
1  i can go from feeling so hopeless to so damned...  sadness
2   im grabbing a minute to post i feel greedy wrong    anger
3  i am ever feeling nostalgic about the fireplac...     love
4                               i am feeling grouchy    anger

In [16]:
df.isnull().sum()

text       0
emotion    0
dtype: int64

In [17]:
unique_emotions = df['emotion'].unique()
print("Unique emotions:", unique_emotions)
emotion_number = {}
i=0
for emo in unique_emotions:
    emotion_number[emo] = i
    i+=1

df['emotion'] = df['emotion'].map(emotion_number)

Unique emotions: ['sadness' 'anger' 'love' 'surprise' 'fear' 'joy']

In [18]:
df.head()

                                                text  emotion
0                            i didnt feel humiliated        0
1  i can go from feeling so hopeless to so damned...        0
2   im grabbing a minute to post i feel greedy wrong        1
3  i am ever feeling nostalgic about the fireplac...        2
4                               i am feeling grouchy        1

In [19]:
df['text'] = df['text'].str.lower()  # Convert text to lowercase

In [20]:
import string

def remove_punctuation(text):
    return text.translate(str.maketrans('', '', string.punctuation))

In [21]:
df['text'] = df['text'].apply(remove_punctuation)  # Remove punctuation from text

In [22]:
df

                                                    text  emotion
0                                i didnt feel humiliated        0
1      i can go from feeling so hopeless to so damned...        0
2       im grabbing a minute to post i feel greedy wrong        1
3      i am ever feeling nostalgic about the fireplac...        2
4                                   i am feeling grouchy        1
...                                                  ...      ...
15995  i just had a very brief time in the beanbag an...        0
15996  i am now turning and i feel pathetic that i am...        0
15997                     i feel strong and good overall        5
15998  i feel like this was such a rude comment and i...        1
15999  i know a lot but i feel so stupid because i ca...        0

[16000 rows x 2 columns]

In [23]:
def remove_numbers(text):
    return ''.join([i for i in text if not i.isdigit()])
df['text'] = df['text'].apply(remove_numbers)  # Remove numbers from text

In [24]:
def remove_emoji(text):
  new = ""
  for i in text:
    if i.isascii():
      new += i
  return new
df['text'] = df['text'].apply(remove_emoji)  # Remove emojis from text

In [25]:
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

In [ ]:
stop_words = set(stopwords.words('english'))
stop_words

{'a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 "he's",
 'her',
 'here',
 'hers',
 'herself',
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 "i'll",
 "i'm",
 "i've",
 'if',
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 're',
 's',
 'same',
 'shan',
 "shan't",
 'she',
 "she'd",
 "she'll",
 "she's",
 'should',
 "should've",
 'shouldn',
 "shouldn't",
 'so',
 'some',
 'such',
 't',
 'than',
 'that',
 "that'll",
 'the',
 'their',
 'theirs',
 'them',
 'themselves',
 'then',
 'there',
 'these',
 'they',
 "they'd",
 "they'll",
 "they're",
 "they've",
 'this',
 'those',
 'through',
 'to',
 'too',
 'under',
 'until',
 'up',
 've',
 'very',
 'was',
 'wasn',
 "wasn't",
 'we',
 "we'd",
 "we'll",
 "we're",
 "we've",
 'were',
 'weren',
 "weren't",
 'what',
 'when',
 'where',
 'which',
 'while',
 'who',
 'whom',
 'why',
 'will',
 'with',
 'won',
 "won't",
 'wouldn',
 "wouldn't",
 'y',
 'you',
 "you'd",
 "you'll",
 "you're",
 "you've",
 'your',
 'yours',
 'yourself',
 'yourselves'}

In [ ]:
df.loc[1]['text']

'i can go from feeling so hopeless to so damned hopeful just from being around someone who cares and is awake'

In [ ]:
def remove_stopwords(text):
    word_tokens = word_tokenize(text)
    filtered_text = [w for w in word_tokens if not w in stop_words]
    return ' '.join(filtered_text)

df['text'] = df['text'].apply(remove_stopwords)  # Remove stop words from text

In [ ]:
df

                                                    text  emotion
0                                  didnt feel humiliated        0
1      go feeling hopeless damned hopeful around some...        0
2              im grabbing minute post feel greedy wrong        1
3      ever feeling nostalgic fireplace know still pr...        2
4                                        feeling grouchy        1
...                                                  ...      ...
15995      brief time beanbag said anna feel like beaten        0
15996  turning feel pathetic still waiting tables sub...        0
15997                           feel strong good overall        5
15998                     feel like rude comment im glad        1
15999                       know lot feel stupid portray        0

[16000 rows x 2 columns]

In [27]:
df.shape

(16000, 2)

In [29]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df['text'], df['emotion'], test_size=0.2, random_state=42)

In [31]:
from sklearn.feature_extraction.text import TfidfVectorizer,CountVectorizer

In [34]:
bow_vectorizer = CountVectorizer()
x_train_bow = bow_vectorizer.fit_transform(X_train)
x_test_bow = bow_vectorizer.transform(X_test)

In [36]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [37]:
nb_model = MultinomialNB()
nb_model.fit(x_train_bow, y_train)

MultinomialNB()

In [40]:
pred_bow = nb_model.predict(x_test_bow)

In [41]:
accuracy_score(y_test, pred_bow)

0.7390625

In [42]:
classification_report(y_test, pred_bow)

'              precision    recall  f1-score   support\n\n           0       0.74      0.94      0.83       946\n           1       0.90      0.56      0.69       427\n           2       0.92      0.16      0.28       296\n           3       1.00      0.04      0.07       113\n           4       0.85      0.50      0.63       397\n           5       0.69      0.97      0.80      1021\n\n    accuracy                           0.74      3200\n   macro avg       0.85      0.53      0.55      3200\nweighted avg       0.78      0.74      0.70      3200\n'

In [44]:
tfid_vector = TfidfVectorizer()
x_train_tfid = tfid_vector.fit_transform(X_train)
x_test_tfid = tfid_vector.transform(X_test)

In [45]:
nb2_model = MultinomialNB()
nb2_model.fit(x_train_tfid, y_train)

MultinomialNB()

In [48]:
pred_nb2 = nb2_model.predict(x_test_tfid)

In [49]:
accuracy_score(y_test, pred_nb2)

0.6175

In [51]:
from sklearn.linear_model import LogisticRegression
log_model = LogisticRegression(max_iter=1000)
log_model.fit(x_train_tfid, y_train)
pred_log = log_model.predict(x_test_tfid)
accuracy_score(y_test, pred_log)

0.84125

In [ ]:
import joblib
joblib.dump(log_model, 'logistic_model.pkl')
joblib.dump(tfid_vector, 'tfidf_vectorizer.pkl')

['tfidf_vectorizer.pkl']